spring:
  application:
    name: visits-service
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: false
    fetch-registry: true

feign:
  circuitbreaker:
    enabled: true
