spring:
  application:
    name: discovery-server
  config:
    # https://docs.spring.io/spring-cloud-config/docs/current/reference/html/
    import: "optional:configserver:"

server:
  port: 8761

eureka:
  environment: dev
  instance:
    hostname: localhost
    appName: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  dashboard:
    enabled: true
    path: /